# Generated by Django 2.2.3 on 2019-07-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_oreder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='oid',
        ),
    ]
